# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0  # Pure Go build - no CGO needed with modernc.org/sqlite
    goos:
      - linux
      - windows  
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64  # Skip Windows ARM64 for now
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: twist

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## TWIST {{ .Tag }} 🚀
    
    Trade Wars 2002 Terminal Interface - Release {{ .Tag }}
  footer: |
    ## Installation
    
    Download the appropriate binary for your platform from the assets above.
    
    **Supported Platforms:**
    - Linux (AMD64, ARM64)
    - macOS (AMD64, ARM64/Apple Silicon)
    - Windows (AMD64)
    
    ### Quick Install (Linux/macOS)
    ```bash
    # Linux AMD64
    curl -L -o twist.tar.gz https://github.com/mrdon/twist/releases/download/{{ .Tag }}/twist_Linux_x86_64.tar.gz
    tar -xzf twist.tar.gz && chmod +x twist && sudo mv twist /usr/local/bin/
    
    # Linux ARM64
    curl -L -o twist.tar.gz https://github.com/mrdon/twist/releases/download/{{ .Tag }}/twist_Linux_arm64.tar.gz
    tar -xzf twist.tar.gz && chmod +x twist && sudo mv twist /usr/local/bin/
    
    # macOS Intel
    curl -L -o twist.tar.gz https://github.com/mrdon/twist/releases/download/{{ .Tag }}/twist_Darwin_x86_64.tar.gz
    tar -xzf twist.tar.gz && chmod +x twist && sudo mv twist /usr/local/bin/
    
    # macOS Apple Silicon
    curl -L -o twist.tar.gz https://github.com/mrdon/twist/releases/download/{{ .Tag }}/twist_Darwin_arm64.tar.gz
    tar -xzf twist.tar.gz && chmod +x twist && sudo mv twist /usr/local/bin/
    ```
    
    ---
    
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser) 🤖
